version: '3.5'

services:
  web:
    container_name: flask_app
    build:
      context: .
    env_file:
      - ./config/.env.dev.api
    networks:
      - postgres
      - redis-net
    ports:
      - 5555:5000
    volumes:
      - ./:/app

  postgres:
    container_name: postgres_container
    image: postgres
    env_file:
      - ./config/.env.dev.db
    volumes:
       - ./database-data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  redis:
    image: "redis:alpine"

    networks:
      - redis-net

networks:
  redis-net:
  postgres:
    driver: bridge

volumes:
    web:
    postgres: